
tasks:
  - name: Mambaforge
    init: |
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.3.361/quarto-1.3.361-linux-amd64.deb
    sudo dpkg -i quarto-1.3.361-linux-amd64.deb
vscode:
  extensions:
    - quarto.quarto