project:
  type: book
  output-dir: docs
  preview:
    port: 4200

book:
  title: "The Little Book of Smiley Plots"
  subtitle: "A collection of ancient DNA patterns and their causes"
  author: "The SPAAM Community"
  date: "25/05/2023"
  license: "CC-BY 4.0"
  page-navigation: true
  downloads: [pdf, epub]
  site-url: https://spaam-community.github.io/little-book-of-smiley-plots
  reader-mode: true
  chapters:
    - index.qmd
    - contributors.qmd
    - intro.qmd
    - part: valid.qmd
      chapters:
        - double-stranded.qmd
        - single-stranded.qmd
        - partial-udg-double-stranded.qmd
        #- partial-udg-single-stranded.qmd
    - part: semi-problematic.qmd
      chapters:
        - proofreading-polymerase.qmd
        - barcode-ligation-bias.qmd
    - part: problematic.qmd
      chapters:
        - insufficient-reads.qmd
        - internal-barcodes.qmd
    #- part: most-wanted.qmd
    #  chapters:
    #    - placeholder.qmd
    #- glossary.qmd
    - references.qmd
  page-footer: "With ❤️ from the SPAAM Community. CC-BY 4.0"

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
  pdf:
    documentclass: scrreprt
