project:
  type: book
  output-dir: docs
  preview:
    port: 4200

book:
  title: "The Little Book of Smiley Plots"
  subtitle: "A collection of ancient DNA patterns and their causes"
  author: "The SPAAM Community"
  date: last-modified
  license: "CC-BY 4.0"
  page-navigation: true
  language: "en-GB"
  back-to-top-navigation: true
  downloads: [pdf, epub]
  site-url: https://spaam-community.github.io/little-book-of-smiley-plots
  repo-url: https://github.com/spaam-community/little-book-of-smiley-plots
  reader-mode: true
  bread-crumbs: true
  chapters:
    - index.qmd
    - contributors.qmd
    - intro.qmd
    - part: valid.qmd
      chapters:
        - double-stranded.qmd
        - single-stranded.qmd
        - partial-udg-double-stranded.qmd
        - partial-udg-single-stranded.qmd
    - part: semi-problematic.qmd
      chapters:
        - proofreading-polymerase.qmd
        - barcode-ligation-bias.qmd
        - softclipping.qmd
        - leftover-adapter.qmd
    - part: problematic.qmd
      chapters:
        - insufficient-reads.qmd
        - internal-barcodes.qmd
    #- part: most-wanted.qmd
    #  chapters:
    #    - placeholder.qmd
    #- glossary.qmd
    - references.qmd
  page-footer: "[CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.en). [Source](https://github.com/spaam-community/little-book-of-smiley-plots). With ❤️ from the [SPAAM Community](https://spaam-community.org)."

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: cyborg
  pdf:
    documentclass: book
